### ISSUE TITLE
Exception when trying to edit Image in Media Module

### ISSUE THREAD

**Issue by franzkugelmann** [neos/metadata#3]
Hi Daniel, i found it again :)
I have all three packages installed and successfully run the indexer. Now if i want to edit any jpg (which has been indexed) in the media module, i get an exception. Opening a png or other formats (which has not been indexed due to missing extractor) works as before.

> Uncaught Exception in Flow
> # 1430075362: Given path "/sites" is not the beginning of "/assets/057b8950-4a7f-4114-90a0-5ca227bf6c81", cannot get a relative path between them.
> 
> InvalidArgumentException thrown in file
> Packages/Application/TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Utility/NodePaths.php in line 205.
> 
> 48 TYPO3\TYPO3CR\Domain\Utility\NodePaths::getRelativePathBetween("/sites", "/assets/057b8950-4a7f-4114-90a0-5ca227bf6c81")

Maybe the issue should be in https://github.com/neos/metadata-contentrepositoryadapter. If i remove that package, i can edit image data again.

**Comment by daniellienert** [comment]
Hey @franzkugelmann, this issue will be fixed with https://github.com/neos/neos-development-collection/pull/1486. As it is a Neos issue, I close this one.
